# Generated by Django 4.0.6 on 2022-07-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=19)),
                ('cpf', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('modelo', models.CharField(max_length=100)),
                ('detalhes', models.CharField(max_length=100)),
                ('relato_do_cliente', models.TextField()),
                ('servico_a_ser_prestado', models.CharField(max_length=255)),
                ('observacao', models.CharField(max_length=255)),
                ('valor_dos_servico', models.IntegerField()),
                ('valor_das_pecas', models.IntegerField()),
                ('valor_total', models.IntegerField()),
            ],
        ),
    ]
